# Docker Compose Ultra Simplificado
# Versão que funciona na maioria dos casos

version: "3.8"

services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: Vitor@56
    volumes:
      - db_data_ultra:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    restart: always
    environment:
      - NODE_ENV=production
    # Aguardar 60s antes de iniciar
    entrypoint: ["sh", "-c", "sleep 60 && npm run start"]

  frontend:
    build: ./frontend
    env_file: ./frontend/.env.production
    ports:
      - "80:3000"
    restart: always
    environment:
      - NODE_ENV=production

volumes:
  db_data_ultra:
