version: "3.8"

networks:
  ecommerce_network:
    driver: bridge

services:
  db:
    image: mysql:8.4
    restart: always
    networks:
      - ecommerce_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: Vitor@56
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 15
      interval: 10s
      start_period: 120s

  backend:
    build: ./backend
    networks:
      - ecommerce_network
    depends_on:
      - db
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    restart: always
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    networks:
      - ecommerce_network
    depends_on:
      - backend
    env_file: ./frontend/.env.production
    ports:
      - "80:3000"
    restart: always
    environment:
      - NODE_ENV=production

volumes:
  db_data:
