# Docker Compose Simplificado
# Use este se o docker-compose.yml principal estiver com problemas

version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: Vitor@56
    volumes:
      - db_data_simple:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    restart: always
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    env_file: ./frontend/.env.production
    ports:
      - "80:3000"
    restart: always
    environment:
      - NODE_ENV=production

volumes:
  db_data_simple:
